### ISSUE TITLE
Doesn't work on tablets.

### ISSUE THREAD

**Issue by peterjschroeder** [igorski/kosm#5]
Tested this app on 2 tablet with accelerometers: Lenovo IdeaTab A2109 and a Galaxy tab E. App installed through google play in Lenovo, had to download apk to install on Galaxy. App starts up and accepts dot creation on both tablets. Moving the screen produces no effects.

**Comment by igorski** [comment]
Hello Peter, Kosm requires both accelerometer and compass sensors (see AndroidManifest). The fact that the Galaxy isn't able to download through Google Play means it doesn't meet one of these requirements (Tab 4 is known not to be supported).

However, as the Lenovo is able to install it through GP, this means that something is amiss. As I don't have access to the two devices you mention, can you use a utility like https://play.google.com/store/apps/details?id=com.miian.android.sensors and provide the full list of supported sensors ? We can take it from there and see what might be the issue.

**Comment by peterjschroeder** [comment]
Okay, didn't realize it needed compass sensors too. The Lenovo only lists Accelerometer and Ambient Light Sensor. Thank You.

**Comment by igorski** [comment]
No problem, I have one question though : you mentioned that you managed to install the app on the Lenovo through Google Play. We now know that it doesn't have the required sensors, but somehow got through the AndroidManifests listed features, can you verify whether you did indeed install through Google Play instead of pushing the APK via another method ?

**Comment by peterjschroeder** [comment]
Just successfully reinstalled again through Google Play. The device is rooted with Cyanogenmod installed.
